# 测试环境
test:
  url: http://172.16.36.212/cas/login
  tenantname: yang
  username: root
  password: 123456


# 生产环境
production:
  url: https://cloud.waiqin365.com
  tenantname: ywcsb
  username: yang
  password: a222222